import {CodeValueItem} from "./types";

export const titlesMock: CodeValueItem[] = [
    {code: "", value: "None"},
    {code: "mr", value: "Mr."},
    {code: "mrs", value: "Mrs."},
    {code: "miss", value: "Miss"},
    {code: "ms", value: "Ms."},
    {code: "dr", value: "Dr."},
    {code: "rev", value: "Rev."}
]

export const countriesMock: CodeValueItem[] = [
    {code: "", value: "Country/Region"},
    {code: "AL", value: "Albania"},
    {code: "AD", value: "Andorra"},
    {code: "AT", value: "Austria"},
    {code: "BY", value: "Belarus"},
    {code: "BE", value: "Belgium"},
    {code: "BA", value: "Bosnia and Herzegovina"},
    {code: "BG", value: "Bulgaria"},
    {code: "CA", value: "Canada"},
    {code: "CN", value: "China"},
    {code: "HR", value: "Croatia"},
    {code: "CY", value: "Cyprus"},
    {code: "CZ", value: "Czech Republic"},
    {code: "DK", value: "Denmark"},
    {code: "EE", value: "Estonia"},
    {code: "FO", value: "Faroe Islands"},
    {code: "FI", value: "Finland"},
    {code: "FR", value: "France"},
    {code: "DE", value: "Germany"},
    {code: "GI", value: "Gibraltar"},
    {code: "GR", value: "Greece"},
    {code: "GL", value: "Greenland"},
    {code: "GG", value: "Guernsey"},
    {code: "VA", value: "Holy See (Vatican City State)"},
    {code: "HK", value: "Hong Kong"},
    {code: "HU", value: "Hungary"},
    {code: "IS", value: "Iceland"},
    {code: "IE", value: "Ireland"},
    {code: "IM", value: "Isle of Man"},
    {code: "IT", value: "Italy"},
    {code: "JP", value: "Japan"},
    {code: "JE", value: "Jersey"},
    {code: "KP", value: "Korea, Democratic People's Republic of"},
    {code: "KR", value: "Korea, Republic of"},
    {code: "LV", value: "Latvia"},
    {code: "LI", value: "Liechtenstein"},
    {code: "LT", value: "Lithuania"},
    {code: "LU", value: "Luxembourg"},
    {code: "MO", value: "Macao"},
    {code: "MK", value: "Macedonia"},
    {code: "MT", value: "Malta"},
    {code: "MD", value: "Moldova"},
    {code: "MC", value: "Monaco"},
    {code: "ME", value: "Montenegro"},
    {code: "NL", value: "Netherlands"},
    {code: "NO", value: "Norway"},
    {code: "PL", value: "Poland"},
    {code: "PT", value: "Portugal"},
    {code: "RO", value: "Romania"},
    {code: "RU", value: "Russian Federation"},
    {code: "SM", value: "San Marino"},
    {code: "RS", value: "Serbia"},
    {code: "SK", value: "Slovakia"},
    {code: "SI", value: "Slovenia"},
    {code: "ES", value: "Spain"},
    {code: "SE", value: "Sweden"},
    {code: "CH", value: "Switzerland"},
    {code: "TW", value: "Taiwan"},
    {code: "TR", value: "Turkey"},
    {code: "UA", value: "Ukraine"},
    {code: "GB", value: "United Kingdom"},
    {code: "US", value: "United States"},
    {code: "VN", value: "Viet Nam"}
]